# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Parent_Aps_Task' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Alamofire','~> 5.0'
  # Pods for Parent_Aps_Task

end
